name: linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version to {% raw %}${{ env.python-version }}{% endraw %}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: {% raw %}${{ env.python-version }}{% endraw %}
      - name: Install package and dev dependencies
        run: |
          uv pip install ".[dev]"
      - name: ruff check
        run: |
          ruff check src/{{cookiecutter.__module_name}} tests
      - name: ruff format
        run: |
          ruff format --check src/{{cookiecutter.__module_name}} tests
      - name: mypy
        run: |
          mypy src/{{cookiecutter.__module_name}} tests
